### ISSUE TITLE
Healthcheck button bugs out 

### ISSUE THREAD

**Issue by vinayakj02** [IRIS-NITK/Staging-Server#14]
# Health Check button bugs out 

![image](https://github.com/IRIS-NITK/Staging-Server/assets/74676945/3a59bc3a-86e9-4e9b-8df9-e9092faa43e0)

Check 

https://github.com/IRIS-NITK/Staging-Server/blob/7c896824cd889fdbcd42f969e30050da4d081a13/main/views.py#L75
https://github.com/IRIS-NITK/Staging-Server/blob/7c896824cd889fdbcd42f969e30050da4d081a13/main/services.py#L38

**Comment by Utkar5hM** [comment]
We'll handle health check differently, Let's have a cronjob like function running inside one of the container. We'll have a health check directly by trying to connect to the deployed containers with the internal port specified instead of having to setup HTTP_AUTH, etc.
